### PR TITLE
Devise 4.x

### PR DESCRIPTION
**Pull request by pkarman**
Update Gemfile to reflect Devise version 4.x

### CODE REVIEW

**Comment by lucasmazza** [comment]
@pkarman, looks like this branch is including the changes from #12 - can you please split it up so we can merge each commit separately? :)

**Comment by pkarman** [comment]
@lucasmazza done, thanks.

**Comment by lostapathy** [comment]
Would we be open to not checking Gemfile.lock into github, at least under gemfiles/ for the travis builds?  That's generally considered best practice (see: http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/) 

In my experience, it makes keeping the CI builds up to date a lot easier. Either bundler's default behavior just works, or you should really lock the dependencies in your gemspec anyway. In the latter case, not versioning Gemfile.lock helps smoke out the issues.

**Comment by karpet** [comment]
@lostapathy that's a fine idea.

I'm actually going to close this PR since (a) I no longer have permission to update the branch and (b) it's over a year old.

**Pull request closed without merging**
